name:                generators
version:             0.1.0.0
github:              "alemoraru/input-expression-generators"
license:             BSD3
author:              "Alexandru Radu Moraru"
maintainer:          "A.R.Moraru-1@student.tudelft.nl"
copyright:           "2021 Alexandru Radu Moraru"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/input-expression-generators#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  generators-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - generators

tests:
  generators-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - generators
